### ISSUE TITLE
Cross domain not working in Firefox

### ISSUE THREAD

**Issue by amaga** [guilhermef/jquery-photo-editor#1]
After setting the access-control-allow-origin http response header in the image to *, Firefox still gives a security error when trying to open an image from a subdomain.

**Comment by amaga** [comment]
Oi Galinho,

Vi que voce fechou o issue, mas nao teve nenhum commit. Vc conseguiu fazer o editor de fotos funcionar no Firefox?

**Comment by guilhermef** [comment]
Eu dei uma olhada e pela tabela de suporte, o Firefox já suporta.
https://developer.mozilla.org/en-US/docs/HTML/CORS_Enabled_Image
