### ISSUE TITLE
Doesn't work with jquery 2

### ISSUE THREAD

**Issue by amaga** [guilhermef/jquery-photo-editor#2]
Fala Galinho,

Fui atualizar o site pro jquery 2 mas o editor nao funciona com ele - alias, nao funciona nem com o 1.9 - só com o 1.7.

**Comment by guilhermef** [comment]
Oi @amaga, esse plugin foi feito todo em cima do 1.7,
acho que não é tão difícil fazer funcionar nas versões mais novas.
Só que agora estou sem tempo pra fazer isso.
